// Package development wires every brick into one place for IDE and REPL
// use. It is generated by goforge; do not edit by hand.
package development

import (
	_ "goforge.dev/etch/bases/etchtui"
	_ "goforge.dev/etch/bases/scrycli"
	_ "goforge.dev/etch/components/hexdump"
)
